In [ ]:
import sys, pathlib

#find the project root containing db/dataraflow_db.py

_p = pathlib.Path.cwd()
while _p != _p.parent and not (_p / "db" / "dataraflow_db.py").exists():
    _p = _p.parent
sys.path.insert(0, str(_p))
from db.dataraflow_db import run_query

In [17]:
from db.dataraflow_db import get_connection

conn = get_connection()
print("Database connection established successfully!")
conn.close()

Database connection established successfully!

In [15]:
df = run_query("SELECT * FROM week06.london_2014")
df.head()

,GMT,Max TemperatureC,Mean TemperatureC,Min TemperatureC,Dew PointC,MeanDew PointC,Min DewpointC,Max Humidity,Mean Humidity,Min Humidity,...,Max VisibilityKm,Mean VisibilityKm,Min VisibilitykM,Max Wind SpeedKm/h,Mean Wind SpeedKm/h,Max Gust SpeedKm/h,Precipitationmm,CloudCover,Events,WindDirDegrees<br />
0,2014-1-1,11,8,6,9,7,4,94,86,73,...,31,11,2,40,26,66.0,9.91,4.0,Rain,186<br />
1,2014-1-2,11,9,6,9,6,4,94,81,60,...,31,15,5,32,21,50.0,1.02,2.0,Rain,214<br />
2,2014-1-3,11,8,6,9,5,2,94,76,54,...,31,12,0,50,29,69.0,7.11,2.0,Rain-Thunderstorm,219<br />
3,2014-1-4,9,6,3,8,6,2,93,85,65,...,31,12,5,35,21,39.0,9.91,4.0,Rain,211<br />
4,2014-1-5,12,7,1,11,4,-1,100,88,77,...,31,14,5,35,16,NaN,0.25,5.0,Rain,199<br />

In [22]:
df = run_query("SELECT * FROM week06.london_2014")
df.head()

,GMT,Max TemperatureC,Mean TemperatureC,Min TemperatureC,Dew PointC,MeanDew PointC,Min DewpointC,Max Humidity,Mean Humidity,Min Humidity,...,Max VisibilityKm,Mean VisibilityKm,Min VisibilitykM,Max Wind SpeedKm/h,Mean Wind SpeedKm/h,Max Gust SpeedKm/h,Precipitationmm,CloudCover,Events,WindDirDegrees<br />
0,2014-1-1,11,8,6,9,7,4,94,86,73,...,31,11,2,40,26,66.0,9.91,4.0,Rain,186<br />
1,2014-1-2,11,9,6,9,6,4,94,81,60,...,31,15,5,32,21,50.0,1.02,2.0,Rain,214<br />
2,2014-1-3,11,8,6,9,5,2,94,76,54,...,31,12,0,50,29,69.0,7.11,2.0,Rain-Thunderstorm,219<br />
3,2014-1-4,9,6,3,8,6,2,93,85,65,...,31,12,5,35,21,39.0,9.91,4.0,Rain,211<br />
4,2014-1-5,12,7,1,11,4,-1,100,88,77,...,31,14,5,35,16,NaN,0.25,5.0,Rain,199<br />

In [23]:
london = run_query("SELECT * FROM week06.london_2014")
london.head()

,GMT,Max TemperatureC,Mean TemperatureC,Min TemperatureC,Dew PointC,MeanDew PointC,Min DewpointC,Max Humidity,Mean Humidity,Min Humidity,...,Max VisibilityKm,Mean VisibilityKm,Min VisibilitykM,Max Wind SpeedKm/h,Mean Wind SpeedKm/h,Max Gust SpeedKm/h,Precipitationmm,CloudCover,Events,WindDirDegrees<br />
0,2014-1-1,11,8,6,9,7,4,94,86,73,...,31,11,2,40,26,66.0,9.91,4.0,Rain,186<br />
1,2014-1-2,11,9,6,9,6,4,94,81,60,...,31,15,5,32,21,50.0,1.02,2.0,Rain,214<br />
2,2014-1-3,11,8,6,9,5,2,94,76,54,...,31,12,0,50,29,69.0,7.11,2.0,Rain-Thunderstorm,219<br />
3,2014-1-4,9,6,3,8,6,2,93,85,65,...,31,12,5,35,21,39.0,9.91,4.0,Rain,211<br />
4,2014-1-5,12,7,1,11,4,-1,100,88,77,...,31,14,5,35,16,NaN,0.25,5.0,Rain,199<br />

In [26]:
cities = run_query("""
    SELECT 'London'    AS city, GMT, [Mean TemperatureC] FROM week06.london_2014
    UNION ALL SELECT 'Beijing',  GMT, [Mean TemperatureC] FROM week06.beijing_pek_2014
    UNION ALL SELECT 'Brasilia', GMT, [Mean TemperatureC] FROM week06.brasilia_bsb_2014
    UNION ALL SELECT 'CapeTown', GMT, [Mean TemperatureC] FROM week06.capetown_cpt_2014
    UNION ALL SELECT 'Delhi',    GMT, [Mean TemperatureC] FROM week06.delhi_del_2014
    UNION ALL SELECT 'Moscow',   GMT, [Mean TemperatureC] FROM week06.moscow_svo_2014
""")
cities.shape   # (2190, 3)

DatabaseError: Execution failed on sql '
    SELECT 'London'    AS city, GMT, [Mean TemperatureC] FROM week06.london_2014
    UNION ALL SELECT 'Beijing',  GMT, [Mean TemperatureC] FROM week06.beijing_pek_2014
    UNION ALL SELECT 'Brasilia', GMT, [Mean TemperatureC] FROM week06.brasilia_bsb_2014
    UNION ALL SELECT 'CapeTown', GMT, [Mean TemperatureC] FROM week06.capetown_cpt_2014
    UNION ALL SELECT 'Delhi',    GMT, [Mean TemperatureC] FROM week06.delhi_del_2014
    UNION ALL SELECT 'Moscow',   GMT, [Mean TemperatureC] FROM week06.moscow_svo_2014
': (pymssql.exceptions.ProgrammingError) (207, b"Invalid column name 'GMT'.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n")
[SQL:
    SELECT 'London'    AS city, GMT, [Mean TemperatureC] FROM week06.london_2014
    UNION ALL SELECT 'Beijing',  GMT, [Mean TemperatureC] FROM week06.beijing_pek_2014
    UNION ALL SELECT 'Brasilia', GMT, [Mean TemperatureC] FROM week06.brasilia_bsb_2014
    UNION ALL SELECT 'CapeTown', GMT, [Mean TemperatureC] FROM week06.capetown_cpt_2014
    UNION ALL SELECT 'Delhi',    GMT, [Mean TemperatureC] FROM week06.delhi_del_2014
    UNION ALL SELECT 'Moscow',   GMT, [Mean TemperatureC] FROM week06.moscow_svo_2014
]
(Background on this error at: https://sqlalche.me/e/21/f405)

In [27]:
london = run_query("SELECT * FROM week06.london_2014")
print(london.columns.tolist())

['GMT', 'Max TemperatureC', 'Mean TemperatureC', 'Min TemperatureC', 'Dew PointC', 'MeanDew PointC', 'Min DewpointC', 'Max Humidity', ' Mean Humidity', ' Min Humidity', ' Max Sea Level PressurehPa', ' Mean Sea Level PressurehPa', ' Min Sea Level PressurehPa', ' Max VisibilityKm', ' Mean VisibilityKm', ' Min VisibilitykM', ' Max Wind SpeedKm/h', ' Mean Wind SpeedKm/h', ' Max Gust SpeedKm/h', 'Precipitationmm', ' CloudCover', ' Events', 'WindDirDegrees<br />']

In [28]:
print("Beijing:", run_query("SELECT TOP 1 * FROM week06.beijing_pek_2014").columns.tolist())
print("Brasilia:", run_query("SELECT TOP 1 * FROM week06.brasilia_bsb_2014").columns.tolist())
print("CapeTown:", run_query("SELECT TOP 1 * FROM week06.capetown_cpt_2014").columns.tolist())
print("Delhi:", run_query("SELECT TOP 1 * FROM week06.delhi_del_2014").columns.tolist())
print("Moscow:", run_query("SELECT TOP 1 * FROM week06.moscow_svo_2014").columns.tolist())

Beijing: ['Date', 'Max TemperatureC', 'Mean TemperatureC', 'Min TemperatureC', 'Dew PointC', 'MeanDew PointC', 'Min DewpointC', 'Max Humidity', ' Mean Humidity', ' Min Humidity', ' Max Sea Level PressurehPa', ' Mean Sea Level PressurehPa', ' Min Sea Level PressurehPa', ' Max VisibilityKm', ' Mean VisibilityKm', ' Min VisibilitykM', ' Max Wind SpeedKm/h', ' Mean Wind SpeedKm/h', ' Max Gust SpeedKm/h', 'Precipitationmm', ' CloudCover', ' Events', 'WindDirDegrees<br />']
Brasilia: ['Date', 'Max TemperatureC', 'Mean TemperatureC', 'Min TemperatureC', 'Dew PointC', 'MeanDew PointC', 'Min DewpointC', 'Max Humidity', ' Mean Humidity', ' Min Humidity', ' Max Sea Level PressurehPa', ' Mean Sea Level PressurehPa', ' Min Sea Level PressurehPa', ' Max VisibilityKm', ' Mean VisibilityKm', ' Min VisibilitykM', ' Max Wind SpeedKm/h', ' Mean Wind SpeedKm/h', ' Max Gust SpeedKm/h', 'Precipitationmm', ' CloudCover', ' Events', 'WindDirDegrees<br />']
CapeTown: ['Date', 'Max TemperatureC', 'Mean TemperatureC', 'Min TemperatureC', 'Dew PointC', 'MeanDew PointC', 'Min DewpointC', 'Max Humidity', ' Mean Humidity', ' Min Humidity', ' Max Sea Level PressurehPa', ' Mean Sea Level PressurehPa', ' Min Sea Level PressurehPa', ' Max VisibilityKm', ' Mean VisibilityKm', ' Min VisibilitykM', ' Max Wind SpeedKm/h', ' Mean Wind SpeedKm/h', ' Max Gust SpeedKm/h', 'Precipitationmm', ' CloudCover', ' Events', 'WindDirDegrees<br />']
Delhi: ['Date', 'Max TemperatureC', 'Mean TemperatureC', 'Min TemperatureC', 'Dew PointC', 'MeanDew PointC', 'Min DewpointC', 'Max Humidity', ' Mean Humidity', ' Min Humidity', ' Max Sea Level PressurehPa', ' Mean Sea Level PressurehPa', ' Min Sea Level PressurehPa', ' Max VisibilityKm', ' Mean VisibilityKm', ' Min VisibilitykM', ' Max Wind SpeedKm/h', ' Mean Wind SpeedKm/h', ' Max Gust SpeedKm/h', 'Precipitationmm', ' CloudCover', ' Events', 'WindDirDegrees<br />']
Moscow: ['Date', 'Max TemperatureC', 'Mean TemperatureC', 'Min TemperatureC', 'Dew PointC', 'MeanDew PointC', 'Min DewpointC', 'Max Humidity', ' Mean Humidity', ' Min Humidity', ' Max Sea Level PressurehPa', ' Mean Sea Level PressurehPa', ' Min Sea Level PressurehPa', ' Max VisibilityKm', ' Mean VisibilityKm', ' Min VisibilitykM', ' Max Wind SpeedKm/h', ' Mean Wind SpeedKm/h', ' Max Gust SpeedKm/h', 'Precipitationmm', ' CloudCover', ' Events', 'WindDirDegrees<br />']

In [30]:
# UNION ALL combines or stacks multiple tables into one long Dataframe.  

cities = run_query("""
    SELECT 'London'    AS city, GMT AS Date, [Mean TemperatureC] FROM week06.london_2014
    UNION ALL SELECT 'Beijing',  Date, [Mean TemperatureC] FROM week06.beijing_pek_2014
    UNION ALL SELECT 'Brasilia', Date, [Mean TemperatureC] FROM week06.brasilia_bsb_2014
    UNION ALL SELECT 'CapeTown', Date, [Mean TemperatureC] FROM week06.capetown_cpt_2014
    UNION ALL SELECT 'Delhi',    Date, [Mean TemperatureC] FROM week06.delhi_del_2014
    UNION ALL SELECT 'Moscow',   Date, [Mean TemperatureC] FROM week06.moscow_svo_2014
""")
cities.shape

(2190, 3)

In [35]:
# computing Aggregate

avg_by_city = run_query("""
    SELECT 'London' AS city, AVG([Mean TemperatureC]) AS avg_temp FROM week06.london_2014
    UNION ALL SELECT 'Delhi', AVG([Mean TemperatureC]) FROM week06.delhi_del_2014
""")
print(avg_by_city)

     city  avg_temp
0  London        12
1   Delhi        13

In [41]:
# pull raw rows and aggregate in pandas

cities.groupby("city")["Mean TemperatureC"].mean()

city
Beijing     13.364384
Brasilia    22.895890
CapeTown    17.567123
Delhi       13.709589
London      12.328767
Moscow       5.994521
Name: Mean TemperatureC, dtype: float64

In [44]:
cities.to_csv("cities_mean_temp.csv", index=False)

In [45]:
who = run_query("SELECT * FROM week06.who_pop_tb_all")
who.head()

       Country  Population (1000s)  TB deaths
0  Afghanistan               30552   13000.00
1      Albania                3173      20.00
2      Algeria               39208    5100.00
3      Andorra                  79       0.26
4       Angola               21472    6900.00

In [ ]:
# Intermediate SQL for Data Analysts


# --- Connect to the cohort database (read-only) ---
import sys, pathlib, re
_p = pathlib.Path.cwd()
while _p != _p.parent and not (_p / "db" / "dataraflow_db.py").exists():
    _p = _p.parent
sys.path.insert(0, str(_p))
from db.dataraflow_db import run_query, get_engine, get_connection

import pandas as pd
pd.set_option("display.max_columns", 50)
pd.set_option("display.width", 200)
pd.set_option("display.float_format", "{:,.2f}".format)

_BLOCKED = re.compile(
    r"\b(INSERT|UPDATE|DELETE|MERGE|DROP|ALTER|CREATE|TRUNCATE|EXEC|EXECUTE|GRANT|REVOKE|DENY|INTO|BACKUP|RESTORE)\b",
    re.IGNORECASE,
)

def q(sql: str) -> pd.DataFrame:
    """Run a read-only query and return a DataFrame.

    String literals and comments are stripped before the safety check, so a value
    like 'Delete me' inside quotes is fine.
    """
    scrubbed = re.sub(r"'([^']|'')*'", "''", sql)           # string literals
    scrubbed = re.sub(r"--[^\n]*", "", scrubbed)              # -- comments
    scrubbed = re.sub(r"/\*.*?\*/", "", scrubbed, flags=re.S) # /* comments */
    hit = _BLOCKED.search(scrubbed)
    if hit:
        raise PermissionError(
            f"'{hit.group(0).upper()}' is not allowed: this notebook is read-only. "
            "Shape your data inside the SELECT, or in pandas."
        )
    return run_query(sql)

q("SELECT DB_NAME() AS database_name, CURRENT_USER AS logged_in_as, SYSDATETIME() AS server_time")

  database_name     logged_in_as                server_time
0  assessmentDB  intern_readonly 2026-10-13 20:04:53.150422

In [48]:
try:
    q("DELETE FROM week06.london_2014")
except PermissionError as e:
    print("Blocked as expected ->", e)

Blocked as expected -> 'DELETE' is not allowed: this notebook is read-only. Shape your data inside the SELECT, or in pandas.

In [49]:
conn = get_connection()
try:
    cur = conn.cursor()
    cur.execute("UPDATE week06.london_2014 SET [Mean TemperatureC] = 0 WHERE 1 = 0")
    print("Unexpected: the server accepted the statement. Tell the admin the account isn't read-only.")
except Exception as e:
    print("Server refused, as expected ->", str(e)[:160])
finally:
    conn.rollback()
    conn.close()

Server refused, as expected -> (229, b"The UPDATE permission was denied on the object 'london_2014', database 'assessmentDB', schema 'week06'.DB-Lib error message 20018, severity 14:\nGeneral

In [51]:
tables = run_query("""
    SELECT TABLE_SCHEMA AS schema_name, TABLE_NAME AS table_name, TABLE_TYPE
    FROM INFORMATION_SCHEMA.TABLES
    ORDER BY TABLE_SCHEMA, TABLE_NAME
""")
print(len(tables), "tables")
tables

67 tables

   schema_name                     table_name  TABLE_TYPE
0          sys        database_firewall_rules        VIEW
1       week06               beijing_pek_2014  BASE TABLE
2       week06              brasilia_bsb_2014  BASE TABLE
3       week06              capetown_cpt_2014  BASE TABLE
4       week06                 delhi_del_2014  BASE TABLE
..         ...                            ...         ...
62      week19                shopping_center  BASE TABLE
63      week19     task1_kmeans_customer_data  BASE TABLE
64      week19  task2_hierarchical_plant_data  BASE TABLE
65      week19            task3_nlp_text_data  BASE TABLE
66      week19                           wine  BASE TABLE

[67 rows x 3 columns]

In [52]:
# Tables per schema (each schema is one week of the programme)
q("""
    SELECT TABLE_SCHEMA AS schema_name, COUNT(*) AS n_tables
    FROM INFORMATION_SCHEMA.TABLES
    GROUP BY TABLE_SCHEMA
    ORDER BY TABLE_SCHEMA
""")

   schema_name  n_tables
0          sys         1
1       week06         8
2       week07         1
3       week08         3
4       week09         3
5       week14        10
6       week15         8
7       week16         9
8       week17         8
9       week18         7
10      week19         9

In [53]:
# Every column of the London weather table, with its type, in table order
q("""
    SELECT ORDINAL_POSITION AS pos, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'week06' AND TABLE_NAME = 'london_2014'
    ORDER BY ORDINAL_POSITION
""")

    pos                  COLUMN_NAME DATA_TYPE IS_NULLABLE
0     1                          GMT   varchar         YES
1     2             Max TemperatureC    bigint         YES
2     3            Mean TemperatureC    bigint         YES
3     4             Min TemperatureC    bigint         YES
4     5                   Dew PointC    bigint         YES
5     6               MeanDew PointC    bigint         YES
6     7                Min DewpointC    bigint         YES
7     8                 Max Humidity    bigint         YES
8     9                Mean Humidity    bigint         YES
9    10                 Min Humidity    bigint         YES
10   11    Max Sea Level PressurehPa    bigint         YES
11   12   Mean Sea Level PressurehPa    bigint         YES
12   13    Min Sea Level PressurehPa    bigint         YES
13   14             Max VisibilityKm    bigint         YES
14   15            Mean VisibilityKm    bigint         YES
15   16             Min VisibilitykM    bigint         YES
16   17           Max Wind SpeedKm/h    bigint         YES
17   18          Mean Wind SpeedKm/h    bigint         YES
18   19           Max Gust SpeedKm/h     float         YES
19   20              Precipitationmm     float         YES
20   21                   CloudCover     float         YES
21   22                       Events   varchar         YES
22   23         WindDirDegrees<br />   varchar         YES

In [57]:
# 1.2  Hidden spaces in column names (a real problem in this database)

q("""
    SELECT DISTINCT '[' + COLUMN_NAME + ']' AS exact_name_to_use
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'week06' AND COLUMN_NAME LIKE ' %'      -- starts with a space
    ORDER BY exact_name_to_use
""")

                exact_name_to_use
0                   [ CloudCover]
1                       [ Events]
2           [ Max Gust SpeedKm/h]
3    [ Max Sea Level PressurehPa]
4             [ Max VisibilityKm]
5           [ Max Wind SpeedKm/h]
6                [ Mean Humidity]
7   [ Mean Sea Level PressurehPa]
8            [ Mean VisibilityKm]
9          [ Mean Wind SpeedKm/h]
10                [ Min Humidity]
11   [ Min Sea Level PressurehPa]
12            [ Min VisibilitykM]

In [58]:
# 1.3 Find a column anywhere in the database

q("""
    SELECT TABLE_SCHEMA + '.' + TABLE_NAME AS table_name, COLUMN_NAME, DATA_TYPE
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE COLUMN_NAME LIKE '%Income%' OR COLUMN_NAME = 'Age'
    ORDER BY table_name
""")

                                       table_name          COLUMN_NAME DATA_TYPE
0               week14.assignment1_ecommerce_data                  Age     float
1               week14.assignment1_ecommerce_data        Annual_Income     float
2                                     week14.data                  Age     float
3                       week14.housing_price_data                  Age    bigint
4                  week14.task1_data_with_missing                  Age     float
5                  week14.task1_data_with_missing               Income     float
6                   week14.task2_categorical_data                  Age    bigint
7                       week14.task3_scaling_data                  Age    bigint
8                 week16.assignment1_house_prices                  Age    bigint
9           week16.assignment2_marketing_campaign                  Age    bigint
10          week16.assignment2_marketing_campaign               Income    bigint
11                 week16.assignment3_credit_risk                  Age    bigint
12                 week16.assignment3_credit_risk               Income    bigint
13                 week16.assignment3_credit_risk       Debt_to_Income     float
14               week16.customer_churn_prediction                  Age    bigint
15                           week16.customer_list                  Age    bigint
16      week17.assignment1_product_recommendation                  Age    bigint
17      week17.assignment1_product_recommendation        Annual_Income    bigint
18           week17.assignment2_medical_diagnosis                  Age    bigint
19                           week17.customer_list                  Age    bigint
20                week17.loan_approval_prediction     Applicant_Income    bigint
21                week17.loan_approval_prediction   Coapplicant_Income    bigint
22                week17.loan_approval_prediction                  Age    bigint
23                 week17.task1_knn_customer_data                  Age    bigint
24  week18.assignment1_decision_tree_optimization                  Age    bigint
25  week18.assignment1_decision_tree_optimization        Annual_Income    bigint
26       week18.assignment3_classifier_comparison                  Age    bigint
27                           week18.customer_list                  Age    bigint
28           week18.employee_attrition_prediction                  Age    bigint
29           week18.employee_attrition_prediction       Monthly_Income    bigint
30       week18.task1_decision_tree_customer_data                  Age    bigint
31       week18.task2_random_forest_customer_data                  Age    bigint
32                 week19.customer_analytics_data                  Age    bigint
33                 week19.customer_analytics_data        Annual_Income     float
34                         week19.shopping_center                  Age    bigint
35                         week19.shopping_center  Annual Income in K$    bigint
36              week19.task1_kmeans_customer_data                  Age    bigint
37              week19.task1_kmeans_customer_data        Annual_Income     float

In [59]:
# 1.4 Profile a table before you trust it

q("""
    SELECT
        COUNT(*)                                   AS n_rows,
        COUNT(DISTINCT Gender)                     AS n_gender_values,
        SUM(CASE WHEN Gender IS NULL THEN 1 ELSE 0 END)           AS missing_gender,
        SUM(CASE WHEN Applicant_Income IS NULL THEN 1 ELSE 0 END) AS missing_income,
        SUM(CASE WHEN Loan_Amount IS NULL THEN 1 ELSE 0 END)      AS missing_loan_amount,
        MIN(Applicant_Income)                      AS min_income,
        MAX(Applicant_Income)                      AS max_income
    FROM week17.loan_approval_prediction
""")

   n_rows  n_gender_values  missing_gender  missing_income  missing_loan_amount  min_income  max_income
0     500                2               0               0                    0       17000       80000

In [60]:
# 1.5 Peek, don't dump

q("SELECT TOP 5 * FROM week09.comtrade_milk_uk_monthly_14")

,Classification,Year,Period,Period Desc.,Aggregate Level,Is Leaf Code,Trade Flow Code,Trade Flow,Reporter Code,Reporter,Reporter ISO,Partner Code,Partner,Partner ISO,2nd Partner Code,2nd Partner,2nd Partner ISO,Customs Proc. Code,Customs,Mode of Transport Code,Mode of Transport,Commodity Code,Commodity,Qty Unit Code,Qty Unit,Qty,Alt Qty Unit Code,Alt Qty Unit,Alt Qty,Netweight (kg),Gross weight (kg),Trade Value (US$),CIF Trade Value (US$),FOB Trade Value (US$),Flag
0,HS,2014,201401,January 2014,4,0,1,Imports,826,United Kingdom,None,0,World,None,None,None,None,None,None,None,None,0401,"Milk and cream, neither concentrated nor sweet...",0,None,None,None,None,None,22404316,None,21950747,None,None,0
1,HS,2014,201401,January 2014,4,0,2,Exports,826,United Kingdom,None,0,World,None,None,None,None,None,None,None,None,0401,"Milk and cream, neither concentrated nor sweet...",0,None,None,None,None,None,60497363,None,46923551,None,None,0
2,HS,2014,201401,January 2014,4,0,2,Exports,826,United Kingdom,None,4,Afghanistan,None,None,None,None,None,None,None,None,0401,"Milk and cream, neither concentrated nor sweet...",0,None,None,None,None,None,2520,None,3410,None,None,0
3,HS,2014,201401,January 2014,4,0,2,Exports,826,United Kingdom,None,40,Austria,None,None,None,None,None,None,None,None,0401,"Milk and cream, neither concentrated nor sweet...",0,None,None,None,None,None,21,None,316,None,None,0
4,HS,2014,201401,January 2014,4,0,1,Imports,826,United Kingdom,None,56,Belgium,None,None,None,None,None,None,None,None,0401,"Milk and cream, neither concentrated nor sweet...",0,None,None,None,None,None,1978279,None,4472349,None,None,0

In [62]:
# Exercise 1.1. List every table in the week16 and week17 schemas together with how many columns each one has. Sort by column count, highest first.

q("""
    SELECT TABLE_SCHEMA AS schema_name, TABLE_NAME AS table_name, COUNT(*) AS n_columns
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA IN ('week16', 'week17')
    GROUP BY TABLE_SCHEMA, TABLE_NAME
    ORDER BY n_columns DESC
""")

   schema_name                          table_name  n_columns
0       week16           customer_churn_prediction         19
1       week17            loan_approval_prediction         16
2       week16             assignment3_credit_risk         10
3       week17       assignment2_medical_diagnosis         10
4       week16      assignment2_marketing_campaign          9
5       week16           task3_classification_data          9
6       week16            assignment1_house_prices          8
7       week17  assignment1_product_recommendation          8
8       week17   assignment3_classifier_comparison          7
9       week17              task3_naive_bayes_data          7
10      week17             task1_knn_customer_data          5
11      week16                       customer_list          5
12      week17                       customer_list          5
13      week16         task2_model_evaluation_data          4
14      week17       task2_svm_classification_data          3
15      week16            task1_random_forest_data          2
16      week16                         gaming_data          2

In [65]:
# Exercise 1.2. Profile week16.customer_churn_prediction: total rows, number of distinct Contract_Type values, number of churned customers (Churn = 1), and the min / max of Monthly_Charges.

q("""
    SELECT 
        COUNT(*) AS total_rows,
        COUNT(DISTINCT Contract_Type) AS distinct_contract_types,
        SUM(Churn) AS churned_customers,
        MIN(Monthly_Charges) AS min_monthly_charges,
        MAX(Monthly_Charges) AS max_monthly_charges
    FROM week16.customer_churn_prediction
""")

   total_rows  distinct_contract_types  churned_customers  min_monthly_charges  max_monthly_charges
0         500                        3                228                20.03               119.20

In [66]:
# Anatomy and Style of a SQL Query

q("""
    SELECT TOP 10
           country,
           [NY.GDP.MKTP.CD] / 1e9 AS gdp_billion_usd
    FROM   week08.wb_gdp_2013
    WHERE  [NY.GDP.MKTP.CD] IS NOT NULL
    ORDER BY gdp_billion_usd DESC
""")

                                     country  gdp_billion_usd
0                                      World        76,236.80
1                                High income        52,256.19
2                               OECD members        48,009.76
3                          High income: OECD        45,927.31
4                        Low & middle income        24,011.49
5                              Middle income        23,637.12
6  Europe & Central Asia (all income levels)        22,949.90
7    East Asia & Pacific (all income levels)        20,846.73
8                              North America        18,612.59
9                        Upper middle income        18,155.01

In [67]:
# 2.2 DISTINCT: the unique values of a column (or combination of columns)

q("""
    SELECT DISTINCT [Trade Flow], [Commodity Code], Commodity
    FROM week09.comtrade_milk_uk_monthly_14
    ORDER BY [Trade Flow], [Commodity Code]
""")

  Trade Flow Commodity Code                                          Commodity
0    Exports           0401  Milk and cream, neither concentrated nor sweet...
1    Exports           0402          Milk and cream, concentrated or sweetened
2    Imports           0401  Milk and cream, neither concentrated nor sweet...
3    Imports           0402          Milk and cream, concentrated or sweetened

In [68]:
# 2.3 TOP ... WITH TIES and TOP ... PERCENT
# TOP 5 cuts at exactly 5 rows, even when the 5th and 6th rows tie. WITH TIES keeps every row that ties with the last one. It needs an ORDER BY.

q("""
    SELECT TOP 5 WITH TIES GMT, [Max TemperatureC]
    FROM week06.london_2014
    ORDER BY [Max TemperatureC] DESC
""")

         GMT  Max TemperatureC
0  2014-7-18                30
1  2014-7-23                29
2  2014-7-24                29
3  2014-7-26                29
4  2014-7-17                29

In [69]:
# 2.4 Paging with OFFSET ... FETCH
# This is the standard SQL way to say "skip 10 rows, then give me 5". Dashboards and APIs page through results like this.

q("""
    SELECT country, [SP.POP.TOTL] AS population
    FROM week08.wb_pop_2013
    WHERE [SP.POP.TOTL] IS NOT NULL
    ORDER BY population DESC
    OFFSET 10 ROWS FETCH NEXT 5 ROWS ONLY      -- ranks 11 to 15
""")

                                  country       population
0                                   India 1,279,498,874.00
1                            OECD members 1,263,178,643.00
2                       High income: OECD 1,064,428,332.00
3  Sub-Saharan Africa (all income levels)   948,287,652.00
4    Sub-Saharan Africa (developing only)   947,400,670.00

In [70]:
# Exercise 2.1. Show the 10 least populous entries in week08.wb_pop_2013 (ignore NULLs), with population shown in thousands and rounded to 1 decimal place, in a column called pop_thousands.

q("""
    SELECT TOP 10 country, ROUND([SP.POP.TOTL] / 1000.0, 1) AS pop_thousands
    FROM week08.wb_pop_2013
    WHERE [SP.POP.TOTL] IS NOT NULL
    ORDER BY [SP.POP.TOTL] ASC
""")

                     country  pop_thousands
0                     Tuvalu           9.90
1                      Palau          20.90
2   St. Martin (French part)          31.30
3                 San Marino          31.40
4   Turks and Caicos Islands          33.10
5  Sint Maarten (Dutch part)          36.60
6              Liechtenstein          37.00
7                     Monaco          37.50
8             Faeroe Islands          48.30
9           Marshall Islands          52.80

In [72]:
# 3.1 IN, BETWEEN, NOT

q("""
    SELECT Application_ID, Property_Area, Education, Applicant_Income, Loan_Amount, Loan_Approved
    FROM week17.loan_approval_prediction
    WHERE Property_Area IN ('Urban', 'Semiurban')
      AND Applicant_Income BETWEEN 5000 AND 10000      -- inclusive on both ends
      AND NOT Education = 'Graduate'
    ORDER BY Applicant_Income
""")

Empty DataFrame
Columns: [Application_ID, Property_Area, Education, Applicant_Income, Loan_Amount, Loan_Approved]
Index: []

In [73]:
# Pattern matching with LIKE

q("""
    SELECT [ Events] AS events, COUNT(*) AS n_days
    FROM week06.london_2014
    WHERE [ Events] LIKE '%Rain%'
    GROUP BY [ Events]
    ORDER BY n_days DESC
""")

                       events  n_days
0                        Rain     202
1                    Fog-Rain      17
2           Rain-Thunderstorm      15
3       Fog-Rain-Thunderstorm       2
4  Fog-Rain-Snow-Thunderstorm       1
5                   Rain-Snow       1

In [75]:
# Null

q("""
    SELECT
        (SELECT COUNT(*) FROM week06.london_2014)                            AS all_days,
        (SELECT COUNT(*) FROM week06.london_2014 WHERE [ Events] =  'Rain')     AS rain_only,
        (SELECT COUNT(*) FROM week06.london_2014 WHERE [ Events] <> 'Rain')     AS not_rain_naive,
        (SELECT COUNT(*) FROM week06.london_2014 WHERE [ Events] IS NULL)       AS no_event_recorded,
        (SELECT COUNT(*) FROM week06.london_2014
          WHERE [ Events] <> 'Rain' OR [ Events] IS NULL)                          AS not_rain_correct
""")

   all_days  rain_only  not_rain_naive  no_event_recorded  not_rain_correct
0       365        202              49                114               163

In [76]:
# 3.4 Handling NULLs: COALESCE, ISNULL, NULLIF

q("""
    SELECT TOP 10
        GMT,
        COALESCE([ Events], 'No event')                        AS events_clean,
        Precipitationmm,
        [Max TemperatureC] - [Min TemperatureC]             AS temp_range,
        -- the ratio would crash on a day with zero range; NULLIF turns that into NULL instead
        Precipitationmm / NULLIF([Max TemperatureC] - [Min TemperatureC], 0) AS rain_per_degree_range
    FROM week06.london_2014
    ORDER BY Precipitationmm DESC
""")

          GMT                events_clean  Precipitationmm  temp_range  rain_per_degree_range
0    2014-8-8                        Rain            21.08           7                   3.01
1   2014-8-11           Rain-Thunderstorm            19.05           9                   2.12
2   2014-7-28           Rain-Thunderstorm            17.02           9                   1.89
3   2014-8-25                        Rain            17.02           4                   4.25
4   2014-1-29                        Rain            13.97           2                   6.99
5   2014-6-28                        Rain            13.97           6                   2.33
6  2014-11-23                        Rain            13.97           5                   2.79
7   2014-11-2                        Rain            11.94           6                   1.99
8   2014-11-4  Fog-Rain-Snow-Thunderstorm            11.94          10                   1.19
9    2014-1-1                        Rain             9.91           5                   1.98

In [77]:
# Exercise 3.1. From week17.loan_approval_prediction, find self-employed applicants whose Previous_Loan_Status is Defaulted but who were still approved. Show ID, income, loan amount and credit history.
q("""
    SELECT Application_ID, Applicant_Income, Loan_Amount, Credit_History
    FROM week17.loan_approval_prediction
    WHERE Self_Employed = 'Yes'
      AND Previous_Loan_Status = 'Defaulted'
      AND Loan_Approved = 1
""")

Empty DataFrame
Columns: [Application_ID, Applicant_Income, Loan_Amount, Credit_History]
Index: []

In [80]:
# Exercise 3.2. How many loan applications have at least one of Gender, Married or Self_Employed missing? (Hint: OR + IS NULL.)

q("""
    SELECT COUNT(*) AS missing_count
    FROM week17.loan_approval_prediction
    WHERE Gender IS NULL 
       OR Married IS NULL
       OR Self_Employed IS NULL
""")

   missing_count
0              0

In [82]:
# 4.1 dtat types and conversions

q("""
    SELECT TOP 5
        GMT                                  AS raw_value,
        TRY_CONVERT(date, GMT)               AS as_date,
        DATENAME(weekday, TRY_CONVERT(date, GMT)) AS day_name,
        MONTH(TRY_CONVERT(date, GMT))        AS month_no,
        DATENAME(month, TRY_CONVERT(date, GMT))   AS month_name,
        DATEPART(quarter, TRY_CONVERT(date, GMT)) AS qtr,
        EOMONTH(TRY_CONVERT(date, GMT))      AS month_end
    FROM week06.london_2014
""")

  raw_value     as_date   day_name  month_no month_name  qtr   month_end
0  2014-1-1  2014-01-01  Wednesday         1    January    1  2014-01-31
1  2014-1-2  2014-01-02   Thursday         1    January    1  2014-01-31
2  2014-1-3  2014-01-03     Friday         1    January    1  2014-01-31
3  2014-1-4  2014-01-04   Saturday         1    January    1  2014-01-31
4  2014-1-5  2014-01-05     Sunday         1    January    1  2014-01-31

In [ ]:
# 4.2 Date arithmetic

q("""
    SELECT TRY_CONVERT(date, GMT) AS day, [Mean TemperatureC],
           DATEDIFF(day, DATEFROMPARTS(2014, 1, 1), TRY_CONVERT(date, GMT)) + 1 AS day_of_year
    FROM week06.london_2014
    WHERE TRY_CONVERT(date, GMT) BETWEEN DATEFROMPARTS(2014, 12, 8) AND DATEFROMPARTS(2014, 12, 12)
    ORDER BY day
""")

          day  Mean TemperatureC  day_of_year
0  2014-12-08                  4          342
1  2014-12-09                  6          343
2  2014-12-10                  7          344
3  2014-12-11                  8          345
4  2014-12-12                  6          346

In [84]:
# 4.3 string functions

q("""
    SELECT DISTINCT TOP 5
        Period,
        DATEFROMPARTS(Period / 100, Period % 100, 1)               AS period_start,
        CONCAT(DATENAME(month, DATEFROMPARTS(Period / 100, Period % 100, 1)), ' ', Period / 100) AS period_label
    FROM week09.comtrade_milk_uk_monthly_14
    ORDER BY Period
""")

   Period period_start   period_label
0  201401   2014-01-01   January 2014
1  201402   2014-02-01  February 2014
2  201403   2014-03-01     March 2014
3  201404   2014-04-01     April 2014
4  201405   2014-05-01       May 2014

In [85]:
q("""
    SELECT DISTINCT
        Commodity,
        LEN(Commodity)                                      AS n_chars,
        LEFT(Commodity, CHARINDEX(',', Commodity + ',') - 1) AS short_name,
        UPPER(REPLACE(Commodity, 'Milk and cream', 'M&C'))  AS abbreviated
    FROM week09.comtrade_milk_uk_monthly_14
""")

                                           Commodity  n_chars      short_name                              abbreviated
0          Milk and cream, concentrated or sweetened       41  Milk and cream           M&C, CONCENTRATED OR SWEETENED
1  Milk and cream, neither concentrated nor sweet...       50  Milk and cream  M&C, NEITHER CONCENTRATED NOR SWEETENED

In [86]:
# the integer-division trap

q("""
    SELECT
        AVG(Loan_Approved)                         AS wrong_rate,      -- integer average, truncated
        AVG(CAST(Loan_Approved AS float))          AS right_rate_cast,
        AVG(1.0 * Loan_Approved)                   AS right_rate_trick,
        7 / 2                                      AS int_division,    -- 3
        7 / 2.0                                    AS dec_division     -- 3.5
    FROM week17.loan_approval_prediction
""")

   wrong_rate  right_rate_cast  right_rate_trick  int_division  dec_division
0           0             0.67              0.67             3          3.50

In [87]:
# Exercise 4.1. For London, count how many days fell on each weekday (Monday...Sunday) where Precipitationmm > 0. Sort by the number of wet days, most first.

q("""
    SELECT DATENAME(weekday, TRY_CONVERT(date, GMT)) AS weekday_name,
           COUNT(*) AS wet_days_count
    FROM week06.london_2014
    WHERE Precipitationmm > 0
    GROUP BY DATENAME(weekday, TRY_CONVERT(date, GMT))
    ORDER BY wet_days_count DESC
""")

  weekday_name  wet_days_count
0       Monday              30
1       Friday              29
2      Tuesday              28
3    Wednesday              24
4     Saturday              23
5     Thursday              19
6       Sunday              17

In [88]:
# Exercise 4.2. Compute the churn rate (as a percentage with 1 decimal place) in week16.customer_churn_prediction. Avoid the integer-division trap!

q("""
    SELECT 
        ROUND(100.0 * SUM(Churn) / COUNT(*), 1) AS churn_rate_percentage
    FROM week16.customer_churn_prediction
""")

   churn_rate_percentage
0                  45.60

In [90]:
# 5.1 Bucketing a numeric column

q("""
    SELECT
        CASE
            WHEN Applicant_Income <  3000 THEN '1. < 3k'
            WHEN Applicant_Income <  6000 THEN '2. 3k-6k'
            WHEN Applicant_Income < 10000 THEN '3. 6k-10k'
            WHEN Applicant_Income IS NULL THEN '9. unknown'
            ELSE '4. 10k+'
        END                                          AS income_band,
        COUNT(*)                                     AS applicants,
        ROUND(100.0 * AVG(1.0 * Loan_Approved), 1)   AS approval_rate_pct
    FROM week17.loan_approval_prediction
    GROUP BY
        CASE
            WHEN Applicant_Income <  3000 THEN '1. < 3k'
            WHEN Applicant_Income <  6000 THEN '2. 3k-6k'
            WHEN Applicant_Income < 10000 THEN '3. 6k-10k'
            WHEN Applicant_Income IS NULL THEN '9. unknown'
            ELSE '4. 10k+'
        END
    ORDER BY income_band
""")

  income_band  applicants  approval_rate_pct
0     4. 10k+         500              66.80

In [91]:
# 5.2 Conditional aggregation: the most useful pattern in analytics
# Put a CASE inside an aggregate to compute several filtered metrics in a single pass. This is how you build a pivot-style summary without PIVOT.

q("""
    SELECT
        Contract_Type,
        COUNT(*)                                                      AS customers,
        SUM(CASE WHEN Churn = 1 THEN 1 ELSE 0 END)                    AS churned,
        ROUND(100.0 * AVG(CASE WHEN Churn = 1 THEN 1.0 ELSE 0 END), 1) AS churn_rate_pct,
        ROUND(AVG(CASE WHEN Churn = 1 THEN Monthly_Charges END), 2)   AS avg_charge_churned,
        ROUND(AVG(CASE WHEN Churn = 0 THEN Monthly_Charges END), 2)   AS avg_charge_stayed
    FROM week16.customer_churn_prediction
    GROUP BY Contract_Type
    ORDER BY churn_rate_pct DESC
""")

    Contract_Type  customers  churned  churn_rate_pct  avg_charge_churned  avg_charge_stayed
0  Month-to-Month        158       91           57.60               65.03              62.86
1        One Year        165       89           53.90               61.22              63.01
2        Two Year        177       48           27.10               70.76              62.79

In [93]:
# 5.3 IIF: a shortcut for a two-way CASE (T-SQL only)

q("""
    SELECT
        IIF([Mean TemperatureC] >= 15, 'warm', 'cool') AS day_type,
        COUNT(*)                                       AS n_days,
        ROUND(AVG(Precipitationmm), 2)                 AS avg_rain_mm
    FROM week06.london_2014
    GROUP BY IIF([Mean TemperatureC] >= 15, 'warm', 'cool')
""")

  day_type  n_days  avg_rain_mm
0     cool     240         1.51
1     warm     125         1.12

In [96]:
# Exercise 5.1. Classify churn customers by Tenure into 'New (<12m)', 'Established (12-36m)' and 'Loyal (36m+)'. For each group show the customer count and churn rate %.

q("""
    SELECT
        CASE WHEN Tenure < 12 THEN 'New (<12m)'
             WHEN Tenure < 36 THEN 'Established (12-36m)'
             ELSE 'Loyal (36m+)' END              AS tenure_group,
        COUNT(*)                                  AS customers,
        ROUND(100.0 * AVG(1.0 * Churn), 1)        AS churn_rate_pct
    FROM week16.customer_churn_prediction
    GROUP BY CASE WHEN Tenure < 12 THEN 'New (<12m)'
                  WHEN Tenure < 36 THEN 'Established (12-36m)'
                  ELSE 'Loyal (36m+)' END
    ORDER BY churn_rate_pct DESC
""")

           tenure_group  customers  churn_rate_pct
0            New (<12m)         73           57.50
1  Established (12-36m)        175           45.70
2          Loyal (36m+)        252           42.10

In [101]:
# Exercise 5.2. Using conditional aggregation, produce one row per Property_Area with columns: applications, approved, rejected, approved_with_bad_credit (approved AND Credit_History = 0).

q("""
    SELECT Property_Area,
           COUNT(*)                                                         AS applications,
           SUM(CASE WHEN Loan_Approved = 1 THEN 1 ELSE 0 END)               AS approved,
           SUM(CASE WHEN Loan_Approved = 0 THEN 1 ELSE 0 END)               AS rejected,
           SUM(CASE WHEN Loan_Approved = 1 AND Credit_History = 0 THEN 1 ELSE 0 END) AS approved_with_bad_credit
    FROM week17.loan_approval_prediction
    GROUP BY Property_Area
""")

  Property_Area  applications  approved  rejected  approved_with_bad_credit
0         Rural           166         0       166                         0
1     Semiurban           167       167         0                         0
2         Urban           167       167         0                         0

In [102]:
# 6.1 The three COUNTs

q("""
    SELECT COUNT(*)                 AS all_rows,
           COUNT([ Events])            AS rows_with_an_event,
           COUNT(DISTINCT [ Events])   AS distinct_event_types
    FROM week06.london_2014
""")

   all_rows  rows_with_an_event  distinct_event_types
0       365                 251                     7

In [104]:
# 6.2 GROUP BY several columns, then HAVING


q("""
    SELECT Partner,
           COUNT(DISTINCT Period)            AS active_months,
           SUM([Trade Value (US$)])          AS total_value_usd
    FROM week09.comtrade_milk_uk_monthly_14
    WHERE [Trade Flow] = 'Exports'          -- row filter
      AND Partner <> 'World'                -- remove the "World" total row, if present
    GROUP BY Partner
    HAVING COUNT(DISTINCT Period) >= 10     -- group filter
    ORDER BY total_value_usd DESC
""")

                     Partner  active_months  total_value_usd
0                    Ireland             12        421228441
1                    Algeria             12         93753841
2                Netherlands             12         68649082
3                    Germany             12         36096633
4                     France             12         34622982
5                    Belgium             12         29343007
6                      China             12         27317861
7       China, Hong Kong SAR             12         19847947
8              Côte d'Ivoire             11         17732776
9                     Angola             11         13305815
10                   Nigeria             12         12932371
11                    Guinea             12         12018176
12                   Lebanon             12         10400613
13                     Congo             12          6407358
14                 Singapore             11          4551284
15              Burkina Faso             10          4239833
16                     Spain             12          3548528
17      United Arab Emirates             12          3264368
18                   Denmark             12          2908457
19                   Finland             12          1761424
20                    Poland             11          1596374
21                    Kuwait             10          1392807
22  United States of America             12          1285146
23              South Africa             10           918533
24                  Viet Nam             12           883491
25                 Sri Lanka             11           444448
26                     Malta             12           384794
27  Falkland Isds (Malvinas)             11           381163
28                    Cyprus             12           348028
29                     Italy             12           230573
30                 Gibraltar             11           227660
31                     Japan             10           201051
32                   Hungary             12           188933
33                Czech Rep.             10           147573
34                   Austria             12           136191
35                  Portugal             12            94108
36                    Sweden             12            91538
37              Saint Helena             10            53661
38                    Greece             12            36983

In [105]:
# 6.3 Statistical aggregates
# AVG, MIN, MAX, SUM, STDEV, VAR. Median is covered in Section 11, because it needs a window function.

q("""
    SELECT Education,
           COUNT(*)                         AS n,
           ROUND(AVG(Applicant_Income), 0)  AS mean_income,
           ROUND(STDEV(Applicant_Income), 0) AS sd_income,
           MIN(Applicant_Income)            AS min_income,
           MAX(Applicant_Income)            AS max_income
    FROM week17.loan_approval_prediction
    GROUP BY Education
""")

      Education    n  mean_income  sd_income  min_income  max_income
0      Graduate  334        52796  14,010.00       32000       80000
1  Not Graduate  166        21487   3,139.00       17000       28000

In [106]:
# 6.4 Subtotals and grand totals with ROLLUP

q("""
    SELECT
        CASE WHEN GROUPING([Trade Flow]) = 1 THEN '** ALL FLOWS **' ELSE [Trade Flow] END        AS trade_flow,
        CASE WHEN GROUPING([Commodity Code]) = 1 THEN '(subtotal)' ELSE [Commodity Code] END    AS commodity_code,
        SUM([Trade Value (US$)]) AS total_value_usd
    FROM week09.comtrade_milk_uk_monthly_14
    WHERE Partner <> 'World'
    GROUP BY ROLLUP([Trade Flow], [Commodity Code])
    ORDER BY GROUPING([Trade Flow]), [Trade Flow], GROUPING([Commodity Code]), [Commodity Code]
""")

        trade_flow commodity_code  total_value_usd
0          Exports           0401        433790652
1          Exports           0402        464861283
2          Exports     (subtotal)        898651935
3          Imports           0401        222107771
4          Imports           0402        341777171
5          Imports     (subtotal)        563884942
6  ** ALL FLOWS **     (subtotal)       1462536877

In [107]:
# 6.5 STRING_AGG: collapse many rows into one string

q("""
    SELECT Region,
           COUNT(*) AS customers,
           STRING_AGG(Preferred_Category, ', ') WITHIN GROUP (ORDER BY Preferred_Category) AS categories
    FROM (SELECT DISTINCT Region, Preferred_Category
          FROM week19.customer_analytics_data) AS d
    GROUP BY Region
""")

  Region  customers                                         categories
0   East          6  Beauty, Books, Electronics, Fashion, Home & Ki...
1  North          6  Beauty, Books, Electronics, Fashion, Home & Ki...
2  South          6  Beauty, Books, Electronics, Fashion, Home & Ki...
3   West          6  Beauty, Books, Electronics, Fashion, Home & Ki...

In [108]:
# 6.6 "Column is invalid in the select list..."
# Every column in SELECT must either be in the GROUP BY or be inside an aggregate. This fails:

SELECT Contract_Type, Customer_ID, COUNT(*)   -- Customer_ID is neither grouped nor aggregated
FROM week16.customer_churn_prediction
GROUP BY Contract_Type;

SyntaxError: Invalid star expression (3395423718.py, line 4)

In [112]:
# Exercise 6.1. For week19.customer_analytics_data, show each Region × Payment_Method with the number of customers and average Avg_Order_Value (2 dp). Keep only combinations with more than 25 customers.

q("""
    SELECT Region, Payment_Method,
           COUNT(*)                         AS customers,
           ROUND(AVG(Avg_Order_Value), 2)   AS avg_order_value
    FROM week19.customer_analytics_data
    GROUP BY Region, Payment_Method
    HAVING COUNT(*) > 25
    ORDER BY Region, customers DESC
""")

  Region  Payment_Method  customers  avg_order_value
0   East      Debit Card         40           489.52
1   East     Credit Card         36           492.20
2  North     Credit Card         45           486.00
3  North      Debit Card         42           483.67
4  North  Digital Wallet         35           490.04
5  South     Credit Card         39           484.96
6  South  Digital Wallet         37           499.73
7   West      Debit Card         39           484.94
8   West     Credit Card         35           482.14
9   West  Digital Wallet         26           476.28

In [113]:
# Exercise 6.2. Use ROLLUP on week16.customer_churn_prediction to show churned customers by Internet_Service and Contract_Type, with subtotals per internet service and a grand total.

q("""
    SELECT Internet_Service,
           Contract_Type,
           SUM(Churn) AS churned_customers
    FROM week16.customer_churn_prediction
    GROUP BY ROLLUP(Internet_Service, Contract_Type)
    ORDER BY GROUPING(Internet_Service), Internet_Service, GROUPING(Contract_Type), Contract_Type
""")

   Internet_Service   Contract_Type  churned_customers
0               DSL  Month-to-Month                 28
1               DSL        One Year                 33
2               DSL        Two Year                 13
3               DSL             NaN                 74
4       Fiber Optic  Month-to-Month                 44
5       Fiber Optic        One Year                 32
6       Fiber Optic        Two Year                 25
7       Fiber Optic             NaN                101
8                No  Month-to-Month                 19
9                No        One Year                 24
10               No        Two Year                 10
11               No             NaN                 53
12              NaN             NaN                228

In [ ]:
# Exercise 6.2. Alternative method 


q("""
    SELECT COALESCE(Internet_Service, '** TOTAL **') AS internet_service,
           COALESCE(Contract_Type, '(all)')          AS contract_type,
           SUM(Churn)                                AS churned
    FROM week16.customer_churn_prediction
    GROUP BY ROLLUP(Internet_Service, Contract_Type)
""")

   internet_service   contract_type  churned
0               DSL  Month-to-Month       28
1               DSL        One Year       33
2               DSL        Two Year       13
3               DSL           (all)       74
4       Fiber Optic  Month-to-Month       44
5       Fiber Optic        One Year       32
6       Fiber Optic        Two Year       25
7       Fiber Optic           (all)      101
8                No  Month-to-Month       19
9                No        One Year       24
10               No        Two Year       10
11               No           (all)       53
12      ** TOTAL **           (all)      228

In [ ]:
# 7.2 Inner join of three tables
# The World Bank publishes GDP, life expectancy and population as separate tables. Join them on country:


wb = q("""
    SELECT g.country,
           g.[NY.GDP.MKTP.CD]                       AS gdp_usd,
           p.[SP.POP.TOTL]                          AS population,
           g.[NY.GDP.MKTP.CD] / NULLIF(p.[SP.POP.TOTL], 0) AS gdp_per_capita,
           l.[SP.DYN.LE00.IN]                       AS life_expectancy
    FROM week08.wb_gdp_2013 AS g
    JOIN week08.wb_pop_2013 AS p ON p.country = g.country
    JOIN week08.wb_le_2013  AS l ON l.country = g.country
    WHERE g.[NY.GDP.MKTP.CD] IS NOT NULL
""")
print(wb.shape)
wb.sort_values("gdp_per_capita", ascending=False).head(10)